<a href="https://colab.research.google.com/github/OMMANDLIK/Data_Science_Lab/blob/master/practical3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1:

In [1]:
import numpy as np

# Create a random 3x3 matrix
matrix = np.random.randint(0, 10, size=(3, 3))

print("Created 3x3 Matrix:")
print(matrix)

Created 3x3 Matrix:
[[4 1 7]
 [6 2 5]
 [6 8 0]]


In [2]:
# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print(f"\nDeterminant of the matrix: {determinant}")


Determinant of the matrix: 122.00000000000003


#Task 2

In [6]:
import numpy as np

# Define the matrix A (using the 3x3 matrix from Task 1)
A = np.array([[4, 1, 7],
              [6, 2, 5],
              [6, 8, 0]])

print("Original Matrix A:")
print(A)

# Compute the determinant to check for invertibility
determinant_A = np.linalg.det(A)

if abs(determinant_A) < 1e-9: # Check if determinant is close to zero
    print("\nThe matrix is singular, so its inverse cannot be computed.")
else:
    inverse_A = np.linalg.inv(A)
    print(f"\nDeterminant of A: {determinant_A}")
    print("Inverse of Matrix A:")
    print(inverse_A)

Original Matrix A:
[[4 1 7]
 [6 2 5]
 [6 8 0]]

Determinant of A: 122.00000000000003
Inverse of Matrix A:
[[-0.32786885  0.45901639 -0.07377049]
 [ 0.24590164 -0.3442623   0.18032787]
 [ 0.29508197 -0.21311475  0.01639344]]


Task 3


In [8]:
# Solve the system of linear equations A_solve * solution = B_solve
solution_xy = np.linalg.solve(A_solve, B_solve)

x = solution_xy[0]
y = solution_xy[1]

print(f"\nSolution for x: {x}")
print(f"Solution for y: {y}")


Solution for x: 5.0
Solution for y: 0.0
