<a href="https://colab.research.google.com/github/OMMANDLIK/Data_Science_Lab/blob/master/practicle3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Create a random 3x3 square matrix
matrix = np.random.randint(0, 10, size=(3, 3))

print("The 3x3 matrix is:")
print(matrix)

# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print("\nThe determinant of the matrix is:")
print(determinant)

The 3x3 matrix is:
[[6 6 1]
 [3 8 9]
 [6 9 7]]

The determinant of the matrix is:
26.99999999999998


In [5]:
import numpy as np

# Compute the transpose of the matrix
transposed_matrix = matrix.T

print("\nThe transposed matrix is:")
print(transposed_matrix)


The transposed matrix is:
[[6 3 6]
 [6 8 9]
 [1 9 7]]


In [6]:
import numpy as np

# Define the coefficient matrix A
A = np.array([[2, 3], [4, 5]])

# Define the constant vector B
B = np.array([10, 20])

# Solve for x (where x = [x, y])
solution = np.linalg.solve(A, B)

print("The solution to the system of equations is:")
print(f"x = {solution[0]:.2f}")
print(f"y = {solution[1]:.2f}")

The solution to the system of equations is:
x = 5.00
y = 0.00
